### ISSUE TITLE
bottomContent and topContent not showed

### ISSUE THREAD

**Issue by alexrmg** [moaazsidat/react-native-qrcode-scanner#307] opened 2021-01-06 03:22 UTC
### What's happening?
I set both properties (topContent & bottomContent) with the same code from the tutorial but when camera view comes up neither top or bottom content is showed.

### How can it be reproduced?
I copy exactly same code and follow same steps from tutorial

### Build details?

Galaxy A9, Android, qrcode 1.4.1

**Comment by alexrmg** [comment] 2021-01-06 03:28
![Screenshot_20210105-222333_qshopapp](https://user-images.githubusercontent.com/5226280/103725775-4d4ca980-4fa5-11eb-8011-0ba6e972a56d.jpg)

**Comment by kybishop** [comment] 2021-01-07 16:01
I'm seeing the same issue after following the tutorial.

**Comment by bilalyaqoob** [comment] 2021-01-08 22:33
same issue

**Comment by joaocosta9** [comment] 2021-01-11 17:34
Same problem

**Comment by Hybrol** [comment] 2021-01-11 18:19
Having the same issue

**Comment by brooklyn097** [comment] 2021-01-12 08:31
same here

**Comment by bilalyaqoob** [comment] 2021-01-12 14:56
I fixed the issue

**Comment by bilalyaqoob** [comment] 2021-01-12 14:59
the issue is in the height of the camera area that is why the bottom and top  hide under the camera area you can easily fix it

**Comment by djwillcaine** [comment] 2021-01-12 21:54
Just ran into this issue after updating the package. After some digging, it looks like it got broken in d7ff8325cd557a944d3a7b71165d8dcc509bb6a4 when the camera height got set to the full screen height instead of the screen width. The PR says they couldn't set the height as it was but in my testing it works just fine. I propse reverting this change.

**Comment by moaazsidat** [comment] 2021-01-13 18:32
Merged and released! Thanks for the fix!

**Closed by moaazsidat** 2021-01-13 18:32 UTC
