### ISSUE TITLE
How to stop camera when moving to next Component with React Navigation

### ISSUE THREAD

**Issue by danilovdev** [moaazsidat/react-native-qrcode-scanner#45] opened 2017-11-03 06:28 UTC
I am using Stack Navigator from React Navigation. And when I read QR code and moving to next component but camera still works and vibrates. I set reactivate={true} and reactivateTimeout={5000}

**Comment by hilkeheremans** [comment] 2017-11-05 19:21
This issue is not specific to `react-native-qrcode-scanner` -- it is also valid for `react-native-camera`.

When the Camera component unmounts, the camera will no longer function. In `react-navigation` and in many other navigation libraries, the problem is that screens are often pushed into a stack, but the screens no longer in view do not actually unmount.

In order to avoid this, you would need to (either):
- use a navigation library that unmounts old screens in a stack (not sure if one exists at all)
- detect if the screen holding the camera component is in view or not, and simply not mount the scanner if it isnt --> by far the easiest approach. See `react-navigation`'s docs and issues for tips on this.

**Comment by hilkeheremans** [comment] 2017-11-05 20:12
Also, quick fix since I was just battling the same issue: https://github.com/patlux/react-navigation-is-focused-hoc

**Comment by chopinas** [comment] 2017-12-06 07:54
so easy! just use `this.props.navigation.goBack();`

**Comment by imomer** [comment] 2017-12-14 11:34
So you are saying we have to use `this.props.navigation.goBack();` we cannot navigate to any specific component?

**Comment by adrianolsk** [comment] 2018-03-01 15:59
I workadound is to set a state property to hide the scanner before you navigate

**Comment by imomer** [comment] 2018-03-02 07:05
hide the scanner or unmount it?

is it working for you?

**Comment by JAISWAL007** [comment] 2018-03-12 13:36
just use this.props.navigation.replace("New_Component");

**Comment by Bartlebyy** [comment] 2018-10-08 13:33
I had the same problem. The camera component would not unmount when I switched between tabs. So I took advantage of the `componentDidMount` and added two listeners `willFocus` and `willBlur` and now it works. 
``` 
 componentDidMount() {
    const { navigation } = this.props;
    navigation.addListener('willFocus', () =>
      this.setState({ focusedScreen: true })
    );
    navigation.addListener('willBlur', () =>
      this.setState({ focusedScreen: false })
    );
  }

  render() {
    const { hasCameraPermission, focusedScreen } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else if (focusedScreen){
      return (this.cameraView());
    } else {
      return <View />;
    }
  }
```

**Comment by alexfigtree** [comment] 2018-12-14 21:03
> I had the same problem. The camera component would not unmount when I switched between tabs. So I took advantage of the `componentDidMount` and added two listeners `willFocus` and `willBlur` and now it works.
> 
> ```
>  componentDidMount() {
>     const { navigation } = this.props;
>     navigation.addListener('willFocus', () =>
>       this.setState({ focusedScreen: true })
>     );
>     navigation.addListener('willBlur', () =>
>       this.setState({ focusedScreen: false })
>     );
>   }
> 
>   render() {
>     const { hasCameraPermission, focusedScreen } = this.state;
>     if (hasCameraPermission === null) {
>       return <View />;
>     } else if (hasCameraPermission === false) {
>       return <Text>No access to camera</Text>;
>     } else if (focusedScreen){
>       return (this.cameraView());
>     } else {
>       return <View />;
>     }
>   }
> ```

Helpful link for reference: https://github.com/Bartlebyy/Ariadnes-Thread/blob/master/screens/AddMazeScreen.js

**Comment by Harsh2089** [comment] 2020-04-02 09:15
> I had the same problem. The camera component would not unmount when I switched between tabs. So I took advantage of the `componentDidMount` and added two listeners `willFocus` and `willBlur` and now it works.
> 
> ```
>  componentDidMount() {
>     const { navigation } = this.props;
>     navigation.addListener('willFocus', () =>
>       this.setState({ focusedScreen: true })
>     );
>     navigation.addListener('willBlur', () =>
>       this.setState({ focusedScreen: false })
>     );
>   }
> 
>   render() {
>     const { hasCameraPermission, focusedScreen } = this.state;
>     if (hasCameraPermission === null) {
>       return <View />;
>     } else if (hasCameraPermission === false) {
>       return <Text>No access to camera</Text>;
>     } else if (focusedScreen){
>       return (this.cameraView());
>     } else {
>       return <View />;
>     }
>   }
> ```

You saved my time :)

**Comment by renatobenks** [comment] 2020-05-20 00:40
I'll be closing this one as this is not a problem caused by `react-native-qrcode-scanner` but the `react-native-camera` instead, as discussed here https://github.com/moaazsidat/react-native-qrcode-scanner/issues/12

then it sounds to be duplicated by this other issue as well, take a look on there to make it work 👊

**Closed by renatobenks** 2020-05-20 00:40 UTC
Labels: package: react-native-camera, resolution: duplicate, resolution: solved, type: help wanted

**Comment by svendudink** [comment] 2022-09-12 10:33
adding  ReactDOM.unmountComponentAtNode(QrReader) works for me, hope it will work for you guys as well


 `
 import React, { useState } from 'react';
import { QrReader } from 'react-qr-reader';
import { ReactDOM } from "react";

const Test = (props) => {
  const [data, setData] = useState('No result');

  return (
    <>
      <QrReader
        onResult={(result, error) => {
          if (!!result) {
            setData(result?.text);
 ReactDOM.unmountComponentAtNode(QrReader)
          }

          if (!!error) {
            console.info(error);
          }
        }}
        style={{ width: '100%' }}
      />
      <p>{data}</p>
    </>
  );
}; 
`
